version: "3.7"

services:
  sqlserver_0:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "udanjo2011@"
      ACCEPT_EULA: "Y"
    volumes:
      - type: bind
        source: e/Container-Docker/DBSqlServer/
        target: /var/opt/mssql/data
    container_name: "sqlserver_0"
    ports:
      - "5434:1433"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge